<?php
//$m_dir_data[] = array('m_dir'=>'','m_dir_uid'=>'');
$m_dir_data[] = array('m_dir'=>'Accountants','m_dir_uid'=>'1');
$m_dir_data[] = array('m_dir'=>'Acoustical','m_dir_uid'=>'2');
$m_dir_data[] = array('m_dir'=>'Actuaries','m_dir_uid'=>'3');
$m_dir_data[] = array('m_dir'=>'Acupuncturists','m_dir_uid'=>'4');
$m_dir_data[] = array('m_dir'=>'Adjusters','m_dir_uid'=>'5');
$m_dir_data[] = array('m_dir'=>'Advertising','m_dir_uid'=>'6');
$m_dir_data[] = array('m_dir'=>'African Goods','m_dir_uid'=>'7');
$m_dir_data[] = array('m_dir'=>'Agricultural','m_dir_uid'=>'8');
$m_dir_data[] = array('m_dir'=>'Air Cargo','m_dir_uid'=>'9');
$m_dir_data[] = array('m_dir'=>'Air Conditioning','m_dir_uid'=>'10');
$m_dir_data[] = array('m_dir'=>'Air Duct & Vent Cleaning','m_dir_uid'=>'11');
$m_dir_data[] = array('m_dir'=>'Air Pollution','m_dir_uid'=>'12');
$m_dir_data[] = array('m_dir'=>'Air Purifying','m_dir_uid'=>'13');
$m_dir_data[] = array('m_dir'=>'Air Quality','m_dir_uid'=>'14');
$m_dir_data[] = array('m_dir'=>'Aircraft','m_dir_uid'=>'15');
$m_dir_data[] = array('m_dir'=>'Airflow & Air Balancing','m_dir_uid'=>'16');
$m_dir_data[] = array('m_dir'=>'Airlines','m_dir_uid'=>'17');
$m_dir_data[] = array('m_dir'=>'Airport','m_dir_uid'=>'18');
$m_dir_data[] = array('m_dir'=>'All Terrain Vehicles','m_dir_uid'=>'19');
$m_dir_data[] = array('m_dir'=>'Allergy Treatments','m_dir_uid'=>'20');
$m_dir_data[] = array('m_dir'=>'Alterations Clothing','m_dir_uid'=>'21');
$m_dir_data[] = array('m_dir'=>'Alternative Medicine','m_dir_uid'=>'22');
$m_dir_data[] = array('m_dir'=>'Alternators & Generators','m_dir_uid'=>'23');
$m_dir_data[] = array('m_dir'=>'Aluminum','m_dir_uid'=>'24');
$m_dir_data[] = array('m_dir'=>'Ambulance','m_dir_uid'=>'25');
$m_dir_data[] = array('m_dir'=>'Ammunition','m_dir_uid'=>'26');
$m_dir_data[] = array('m_dir'=>'Amusement','m_dir_uid'=>'27');
$m_dir_data[] = array('m_dir'=>'Animal','m_dir_uid'=>'28');
$m_dir_data[] = array('m_dir'=>'Annuities','m_dir_uid'=>'29');
$m_dir_data[] = array('m_dir'=>'Anodizing','m_dir_uid'=>'30');
$m_dir_data[] = array('m_dir'=>'Answering','m_dir_uid'=>'31');
$m_dir_data[] = array('m_dir'=>'Antiques','m_dir_uid'=>'32');
$m_dir_data[] = array('m_dir'=>'Apartments','m_dir_uid'=>'33');
$m_dir_data[] = array('m_dir'=>'Appliance','m_dir_uid'=>'34');
$m_dir_data[] = array('m_dir'=>'Appraisers','m_dir_uid'=>'35');
$m_dir_data[] = array('m_dir'=>'Apprenticeship','m_dir_uid'=>'36');
$m_dir_data[] = array('m_dir'=>'Aquarium','m_dir_uid'=>'37');
$m_dir_data[] = array('m_dir'=>'Arbitrators','m_dir_uid'=>'38');
$m_dir_data[] = array('m_dir'=>'Arborists','m_dir_uid'=>'39');
$m_dir_data[] = array('m_dir'=>'Archaeologists','m_dir_uid'=>'40');
$m_dir_data[] = array('m_dir'=>'Archery','m_dir_uid'=>'41');
$m_dir_data[] = array('m_dir'=>'Architects','m_dir_uid'=>'42');
$m_dir_data[] = array('m_dir'=>'Armored Vehicles','m_dir_uid'=>'43');
$m_dir_data[] = array('m_dir'=>'Army & Navy','m_dir_uid'=>'44');
$m_dir_data[] = array('m_dir'=>'Airforce & Marines','m_dir_uid'=>'45');
$m_dir_data[] = array('m_dir'=>'Aromatherapy','m_dir_uid'=>'46');
$m_dir_data[] = array('m_dir'=>'Art','m_dir_uid'=>'47');
$m_dir_data[] = array('m_dir'=>'Artificial Eyes','m_dir_uid'=>'48');
$m_dir_data[] = array('m_dir'=>'Artificial Flowers & Trees','m_dir_uid'=>'49');
$m_dir_data[] = array('m_dir'=>'Artificial Limbs','m_dir_uid'=>'50');
$m_dir_data[] = array('m_dir'=>'Artificial Turf','m_dir_uid'=>'51');
$m_dir_data[] = array('m_dir'=>'Artist','m_dir_uid'=>'52');
$m_dir_data[] = array('m_dir'=>'Asbestos','m_dir_uid'=>'53');
$m_dir_data[] = array('m_dir'=>'Asphalt','m_dir_uid'=>'54');
$m_dir_data[] = array('m_dir'=>'Assembly & Fabricating','m_dir_uid'=>'55');
$m_dir_data[] = array('m_dir'=>'Assisted Living','m_dir_uid'=>'56');
$m_dir_data[] = array('m_dir'=>'Associations','m_dir_uid'=>'57');
$m_dir_data[] = array('m_dir'=>'Astrologers','m_dir_uid'=>'58');
$m_dir_data[] = array('m_dir'=>'Attorneys','m_dir_uid'=>'59');
$m_dir_data[] = array('m_dir'=>'Attractions','m_dir_uid'=>'60');
$m_dir_data[] = array('m_dir'=>'Auction','m_dir_uid'=>'61');
$m_dir_data[] = array('m_dir'=>'Audio','m_dir_uid'=>'62');
$m_dir_data[] = array('m_dir'=>'Auto','m_dir_uid'=>'63');
$m_dir_data[] = array('m_dir'=>'Automated Teller Machines','m_dir_uid'=>'64');
$m_dir_data[] = array('m_dir'=>'Automation Equipment','m_dir_uid'=>'65');
$m_dir_data[] = array('m_dir'=>'Awards & Reconition','m_dir_uid'=>'66');
$m_dir_data[] = array('m_dir'=>'Awnings & Canopies','m_dir_uid'=>'67');
$m_dir_data[] = array('m_dir'=>'Baby','m_dir_uid'=>'68');
$m_dir_data[] = array('m_dir'=>'Backflow','m_dir_uid'=>'69');
$m_dir_data[] = array('m_dir'=>'Backhoes','m_dir_uid'=>'70');
$m_dir_data[] = array('m_dir'=>'Badges','m_dir_uid'=>'71');
$m_dir_data[] = array('m_dir'=>'Bagels','m_dir_uid'=>'72');
$m_dir_data[] = array('m_dir'=>'Bags','m_dir_uid'=>'73');
$m_dir_data[] = array('m_dir'=>'Bail Bonds','m_dir_uid'=>'74');
$m_dir_data[] = array('m_dir'=>'Bakers','m_dir_uid'=>'75');
$m_dir_data[] = array('m_dir'=>'Balancing Service','m_dir_uid'=>'76');
$m_dir_data[] = array('m_dir'=>'Balloons','m_dir_uid'=>'77');
$m_dir_data[] = array('m_dir'=>'Ballrooms','m_dir_uid'=>'78');
$m_dir_data[] = array('m_dir'=>'Bands & Orchestras','m_dir_uid'=>'79');
$m_dir_data[] = array('m_dir'=>'Bank','m_dir_uid'=>'80');
$m_dir_data[] = array('m_dir'=>'Banking','m_dir_uid'=>'81');
$m_dir_data[] = array('m_dir'=>'Bankruptcy Assistance','m_dir_uid'=>'82');
$m_dir_data[] = array('m_dir'=>'Banners','m_dir_uid'=>'83');
$m_dir_data[] = array('m_dir'=>'Banquet','m_dir_uid'=>'84');
$m_dir_data[] = array('m_dir'=>'Bar Code','m_dir_uid'=>'85');
$m_dir_data[] = array('m_dir'=>'Bar','m_dir_uid'=>'86');
$m_dir_data[] = array('m_dir'=>'Barbecue','m_dir_uid'=>'87');
$m_dir_data[] = array('m_dir'=>'Barber','m_dir_uid'=>'88');
$m_dir_data[] = array('m_dir'=>'Barricades','m_dir_uid'=>'89');
$m_dir_data[] = array('m_dir'=>'Bars & Taverns','m_dir_uid'=>'90');
$m_dir_data[] = array('m_dir'=>'Bartender','m_dir_uid'=>'91');
$m_dir_data[] = array('m_dir'=>'Baseball','m_dir_uid'=>'92');
$m_dir_data[] = array('m_dir'=>'Basketball','m_dir_uid'=>'93');
$m_dir_data[] = array('m_dir'=>'Bathroom','m_dir_uid'=>'94');
$m_dir_data[] = array('m_dir'=>'Baths','m_dir_uid'=>'95');
$m_dir_data[] = array('m_dir'=>'Bathtubs & Sinks','m_dir_uid'=>'96');
$m_dir_data[] = array('m_dir'=>'Batteries','m_dir_uid'=>'97');
$m_dir_data[] = array('m_dir'=>'Beads','m_dir_uid'=>'98');
$m_dir_data[] = array('m_dir'=>'Bearings','m_dir_uid'=>'99');
$m_dir_data[] = array('m_dir'=>'Beauty','m_dir_uid'=>'100');
$m_dir_data[] = array('m_dir'=>'Bed & Breakfast','m_dir_uid'=>'101');
$m_dir_data[] = array('m_dir'=>'Beds','m_dir_uid'=>'102');
$m_dir_data[] = array('m_dir'=>'Bee','m_dir_uid'=>'103');
$m_dir_data[] = array('m_dir'=>'Beer','m_dir_uid'=>'104');
$m_dir_data[] = array('m_dir'=>'Beverages','m_dir_uid'=>'105');
$m_dir_data[] = array('m_dir'=>'Bible','m_dir_uid'=>'106');
$m_dir_data[] = array('m_dir'=>'Bicycle','m_dir_uid'=>'107');
$m_dir_data[] = array('m_dir'=>'Bill Paying Service','m_dir_uid'=>'108');
$m_dir_data[] = array('m_dir'=>'Billiard','m_dir_uid'=>'109');
$m_dir_data[] = array('m_dir'=>'Billing Service','m_dir_uid'=>'110');
$m_dir_data[] = array('m_dir'=>'Binders','m_dir_uid'=>'111');
$m_dir_data[] = array('m_dir'=>'Bingo','m_dir_uid'=>'112');
$m_dir_data[] = array('m_dir'=>'Biofeedback Therapists','m_dir_uid'=>'113');
$m_dir_data[] = array('m_dir'=>'Biological Products','m_dir_uid'=>'114');
$m_dir_data[] = array('m_dir'=>'Biotechnology','m_dir_uid'=>'115');
$m_dir_data[] = array('m_dir'=>'Bird','m_dir_uid'=>'116');
$m_dir_data[] = array('m_dir'=>'Birth','m_dir_uid'=>'117');
$m_dir_data[] = array('m_dir'=>'Birthday','m_dir_uid'=>'118');
$m_dir_data[] = array('m_dir'=>'Blasting','m_dir_uid'=>'119');
$m_dir_data[] = array('m_dir'=>'Blind','m_dir_uid'=>'120');
$m_dir_data[] = array('m_dir'=>'Blinds','m_dir_uid'=>'121');
$m_dir_data[] = array('m_dir'=>'Blood Banks','m_dir_uid'=>'122');
$m_dir_data[] = array('m_dir'=>'Blood Testing','m_dir_uid'=>'123');
$m_dir_data[] = array('m_dir'=>'Blowers','m_dir_uid'=>'124');
$m_dir_data[] = array('m_dir'=>'Blower Systems','m_dir_uid'=>'125');
$m_dir_data[] = array('m_dir'=>'Blueprinters','m_dir_uid'=>'126');
$m_dir_data[] = array('m_dir'=>'Boat','m_dir_uid'=>'127');
$m_dir_data[] = array('m_dir'=>'Body Piercing','m_dir_uid'=>'128');
$m_dir_data[] = array('m_dir'=>'Boilers','m_dir_uid'=>'129');
$m_dir_data[] = array('m_dir'=>'Bolts & Nuts','m_dir_uid'=>'130');
$m_dir_data[] = array('m_dir'=>'Bonds','m_dir_uid'=>'131');
$m_dir_data[] = array('m_dir'=>'Book','m_dir_uid'=>'132');
$m_dir_data[] = array('m_dir'=>'Bookkeeping','m_dir_uid'=>'133');
$m_dir_data[] = array('m_dir'=>'Boots','m_dir_uid'=>'134');
$m_dir_data[] = array('m_dir'=>'Boring','m_dir_uid'=>'135');
$m_dir_data[] = array('m_dir'=>'Bottlers','m_dir_uid'=>'136');
$m_dir_data[] = array('m_dir'=>'Boutiques','m_dir_uid'=>'137');
$m_dir_data[] = array('m_dir'=>'Bowling','m_dir_uid'=>'138');
$m_dir_data[] = array('m_dir'=>'Boxes','m_dir_uid'=>'139');
$m_dir_data[] = array('m_dir'=>'Braids','m_dir_uid'=>'140');
$m_dir_data[] = array('m_dir'=>'Brakes','m_dir_uid'=>'141');
$m_dir_data[] = array('m_dir'=>'Bras','m_dir_uid'=>'142');
$m_dir_data[] = array('m_dir'=>'Brewers','m_dir_uid'=>'143');
$m_dir_data[] = array('m_dir'=>'Brew Pubs','m_dir_uid'=>'144');
$m_dir_data[] = array('m_dir'=>'Brick','m_dir_uid'=>'145');
$m_dir_data[] = array('m_dir'=>'Bridal','m_dir_uid'=>'146');
$m_dir_data[] = array('m_dir'=>'Bridge Builders','m_dir_uid'=>'147');
$m_dir_data[] = array('m_dir'=>'Bridge Clubs','m_dir_uid'=>'148');
$m_dir_data[] = array('m_dir'=>'Brushes','m_dir_uid'=>'149');
$m_dir_data[] = array('m_dir'=>'Buckles','m_dir_uid'=>'150');
$m_dir_data[] = array('m_dir'=>'Buildings','m_dir_uid'=>'151');
$m_dir_data[] = array('m_dir'=>'Bulkheads','m_dir_uid'=>'152');
$m_dir_data[] = array('m_dir'=>'Bulldozers','m_dir_uid'=>'153');
$m_dir_data[] = array('m_dir'=>'Burglar Alarms','m_dir_uid'=>'154');
$m_dir_data[] = array('m_dir'=>'Bus','m_dir_uid'=>'155');
$m_dir_data[] = array('m_dir'=>'Business','m_dir_uid'=>'156');
$m_dir_data[] = array('m_dir'=>'Butchers','m_dir_uid'=>'157');
$m_dir_data[] = array('m_dir'=>'Cabinet','m_dir_uid'=>'158');
$m_dir_data[] = array('m_dir'=>'Cabins & Cottages','m_dir_uid'=>'159');
$m_dir_data[] = array('m_dir'=>'Cable','m_dir_uid'=>'160');
$m_dir_data[] = array('m_dir'=>'CAD','m_dir_uid'=>'161');
$m_dir_data[] = array('m_dir'=>'Cafes','m_dir_uid'=>'162');
$m_dir_data[] = array('m_dir'=>'Cafeterias','m_dir_uid'=>'163');
$m_dir_data[] = array('m_dir'=>'Cake','m_dir_uid'=>'164');
$m_dir_data[] = array('m_dir'=>'Calenders','m_dir_uid'=>'165');
$m_dir_data[] = array('m_dir'=>'Calibration','m_dir_uid'=>'166');
$m_dir_data[] = array('m_dir'=>'Call Centers','m_dir_uid'=>'167');
$m_dir_data[] = array('m_dir'=>'Calligraphy','m_dir_uid'=>'168');
$m_dir_data[] = array('m_dir'=>'Campers','m_dir_uid'=>'169');
$m_dir_data[] = array('m_dir'=>'Camper Shells','m_dir_uid'=>'170');
$m_dir_data[] = array('m_dir'=>'Campgrounds & RV Parks','m_dir_uid'=>'171');
$m_dir_data[] = array('m_dir'=>'Camping & Backpacking','m_dir_uid'=>'172');
$m_dir_data[] = array('m_dir'=>'Camps','m_dir_uid'=>'173');
$m_dir_data[] = array('m_dir'=>'Cancer','m_dir_uid'=>'174');
$m_dir_data[] = array('m_dir'=>'Candles','m_dir_uid'=>'175');
$m_dir_data[] = array('m_dir'=>'Candy','m_dir_uid'=>'176');
$m_dir_data[] = array('m_dir'=>'Caning','m_dir_uid'=>'177');
$m_dir_data[] = array('m_dir'=>'Canoes','m_dir_uid'=>'178');
$m_dir_data[] = array('m_dir'=>'Cans','m_dir_uid'=>'179');
$m_dir_data[] = array('m_dir'=>'Canvas','m_dir_uid'=>'180');
$m_dir_data[] = array('m_dir'=>'Caps','m_dir_uid'=>'181');
$m_dir_data[] = array('m_dir'=>'Car Washing','m_dir_uid'=>'182');
$m_dir_data[] = array('m_dir'=>'Carbonic Gas','m_dir_uid'=>'183');
$m_dir_data[] = array('m_dir'=>'Career & Vocational','m_dir_uid'=>'184');
$m_dir_data[] = array('m_dir'=>'Cargo & Freight','m_dir_uid'=>'185');
$m_dir_data[] = array('m_dir'=>'Carnivals','m_dir_uid'=>'186');
$m_dir_data[] = array('m_dir'=>'Carpenters','m_dir_uid'=>'187');
$m_dir_data[] = array('m_dir'=>'Carpet & Rug','m_dir_uid'=>'188');
$m_dir_data[] = array('m_dir'=>'Carports','m_dir_uid'=>'189');
$m_dir_data[] = array('m_dir'=>'Cash Register & Supplies','m_dir_uid'=>'190');
$m_dir_data[] = array('m_dir'=>'Casinos','m_dir_uid'=>'191');
$m_dir_data[] = array('m_dir'=>'Catalog Designers','m_dir_uid'=>'192');
$m_dir_data[] = array('m_dir'=>'Caterers','m_dir_uid'=>'193');
$m_dir_data[] = array('m_dir'=>'Cats','m_dir_uid'=>'194');
$m_dir_data[] = array('m_dir'=>'Caulking','m_dir_uid'=>'195');
$m_dir_data[] = array('m_dir'=>'CD, DVD\'s & Blue Ray','m_dir_uid'=>'196');
$m_dir_data[] = array('m_dir'=>'Ceiling Fans','m_dir_uid'=>'197');
$m_dir_data[] = array('m_dir'=>'Cellular','m_dir_uid'=>'198');
$m_dir_data[] = array('m_dir'=>'Cement','m_dir_uid'=>'199');
$m_dir_data[] = array('m_dir'=>'Cemeteries','m_dir_uid'=>'200');
$m_dir_data[] = array('m_dir'=>'Ceramic','m_dir_uid'=>'201');
$m_dir_data[] = array('m_dir'=>'Chains','m_dir_uid'=>'202');
$m_dir_data[] = array('m_dir'=>'Chairs','m_dir_uid'=>'203');
$m_dir_data[] = array('m_dir'=>'Chalkboards','m_dir_uid'=>'204');
$m_dir_data[] = array('m_dir'=>'Chamber of Commerce','m_dir_uid'=>'205');
$m_dir_data[] = array('m_dir'=>'Charitable','m_dir_uid'=>'206');
$m_dir_data[] = array('m_dir'=>'Chauffeur','m_dir_uid'=>'207');
$m_dir_data[] = array('m_dir'=>'Check Cashing','m_dir_uid'=>'208');
$m_dir_data[] = array('m_dir'=>'Check Verification','m_dir_uid'=>'209');
$m_dir_data[] = array('m_dir'=>'Cheerleading','m_dir_uid'=>'210');
$m_dir_data[] = array('m_dir'=>'Cheese','m_dir_uid'=>'211');
$m_dir_data[] = array('m_dir'=>'Chemicals','m_dir_uid'=>'212');
$m_dir_data[] = array('m_dir'=>'Chemists','m_dir_uid'=>'213');
$m_dir_data[] = array('m_dir'=>'Child Care','m_dir_uid'=>'214');
$m_dir_data[] = array('m_dir'=>'Childrens','m_dir_uid'=>'215');
$m_dir_data[] = array('m_dir'=>'Chimney','m_dir_uid'=>'216');
$m_dir_data[] = array('m_dir'=>'Chinese Food','m_dir_uid'=>'217');
$m_dir_data[] = array('m_dir'=>'Chiropractors','m_dir_uid'=>'218');
$m_dir_data[] = array('m_dir'=>'Chlorine','m_dir_uid'=>'219');
$m_dir_data[] = array('m_dir'=>'Chocolate','m_dir_uid'=>'220');
$m_dir_data[] = array('m_dir'=>'Christian','m_dir_uid'=>'221');
$m_dir_data[] = array('m_dir'=>'Christmas','m_dir_uid'=>'222');
$m_dir_data[] = array('m_dir'=>'Church Supplies','m_dir_uid'=>'223');
$m_dir_data[] = array('m_dir'=>'Churches','m_dir_uid'=>'224');
$m_dir_data[] = array('m_dir'=>'Cigar & Cigarette','m_dir_uid'=>'225');
$m_dir_data[] = array('m_dir'=>'Clean Rooms','m_dir_uid'=>'226');
$m_dir_data[] = array('m_dir'=>'Cleaners','m_dir_uid'=>'227');
$m_dir_data[] = array('m_dir'=>'Clinics','m_dir_uid'=>'228');
$m_dir_data[] = array('m_dir'=>'Clocks','m_dir_uid'=>'229');
$m_dir_data[] = array('m_dir'=>'CCTV','m_dir_uid'=>'230');
$m_dir_data[] = array('m_dir'=>'Closets','m_dir_uid'=>'231');
$m_dir_data[] = array('m_dir'=>'Clothing','m_dir_uid'=>'232');
$m_dir_data[] = array('m_dir'=>'Clowns','m_dir_uid'=>'233');
$m_dir_data[] = array('m_dir'=>'Clubs','m_dir_uid'=>'234');
$m_dir_data[] = array('m_dir'=>'Clutches','m_dir_uid'=>'235');
$m_dir_data[] = array('m_dir'=>'Coaching','m_dir_uid'=>'236');
$m_dir_data[] = array('m_dir'=>'Coatings','m_dir_uid'=>'237');
$m_dir_data[] = array('m_dir'=>'Cocktail Lounges','m_dir_uid'=>'238');
$m_dir_data[] = array('m_dir'=>'Coffee','m_dir_uid'=>'239');
$m_dir_data[] = array('m_dir'=>'Coin','m_dir_uid'=>'240');
$m_dir_data[] = array('m_dir'=>'Coin-Op Machines','m_dir_uid'=>'241');
$m_dir_data[] = array('m_dir'=>'Collectibles','m_dir_uid'=>'242');
$m_dir_data[] = array('m_dir'=>'Collection Agencies','m_dir_uid'=>'243');
$m_dir_data[] = array('m_dir'=>'College','m_dir_uid'=>'244');
$m_dir_data[] = array('m_dir'=>'Comedy Clubs','m_dir_uid'=>'245');
$m_dir_data[] = array('m_dir'=>'Comic Books','m_dir_uid'=>'246');
$m_dir_data[] = array('m_dir'=>'Commodity Brokers','m_dir_uid'=>'247');
$m_dir_data[] = array('m_dir'=>'Communication','m_dir_uid'=>'248');
$m_dir_data[] = array('m_dir'=>'Community','m_dir_uid'=>'249');
$m_dir_data[] = array('m_dir'=>'Compactors','m_dir_uid'=>'250');
$m_dir_data[] = array('m_dir'=>'Composite','m_dir_uid'=>'251');
$m_dir_data[] = array('m_dir'=>'Compost','m_dir_uid'=>'252');
$m_dir_data[] = array('m_dir'=>'Compressors','m_dir_uid'=>'253');
$m_dir_data[] = array('m_dir'=>'Computer','m_dir_uid'=>'254');
$m_dir_data[] = array('m_dir'=>'Concerts','m_dir_uid'=>'255');
$m_dir_data[] = array('m_dir'=>'Concession','m_dir_uid'=>'256');
$m_dir_data[] = array('m_dir'=>'Concrete','m_dir_uid'=>'257');
$m_dir_data[] = array('m_dir'=>'Condiments','m_dir_uid'=>'258');
$m_dir_data[] = array('m_dir'=>'Condominiums','m_dir_uid'=>'259');
$m_dir_data[] = array('m_dir'=>'Conference Centers','m_dir_uid'=>'260');
$m_dir_data[] = array('m_dir'=>'Consignment','m_dir_uid'=>'261');
$m_dir_data[] = array('m_dir'=>'Construction','m_dir_uid'=>'262');
$m_dir_data[] = array('m_dir'=>'Consultants','m_dir_uid'=>'263');
$m_dir_data[] = array('m_dir'=>'Contact Lenses','m_dir_uid'=>'264');
$m_dir_data[] = array('m_dir'=>'Containers','m_dir_uid'=>'265');
$m_dir_data[] = array('m_dir'=>'Contractors','m_dir_uid'=>'266');
$m_dir_data[] = array('m_dir'=>'Convenience Stores','m_dir_uid'=>'267');
$m_dir_data[] = array('m_dir'=>'Convention Centers','m_dir_uid'=>'268');
$m_dir_data[] = array('m_dir'=>'Conveyors','m_dir_uid'=>'269');
$m_dir_data[] = array('m_dir'=>'Cookies','m_dir_uid'=>'270');
$m_dir_data[] = array('m_dir'=>'Cooking & Culinary','m_dir_uid'=>'271');
$m_dir_data[] = array('m_dir'=>'Cooling Systems','m_dir_uid'=>'272');
$m_dir_data[] = array('m_dir'=>'Copper','m_dir_uid'=>'273');
$m_dir_data[] = array('m_dir'=>'Copy Machines','m_dir_uid'=>'274');
$m_dir_data[] = array('m_dir'=>'Corporate Rentals','m_dir_uid'=>'275');
$m_dir_data[] = array('m_dir'=>'Corrosion','m_dir_uid'=>'276');
$m_dir_data[] = array('m_dir'=>'Cosmetic','m_dir_uid'=>'277');
$m_dir_data[] = array('m_dir'=>'Cosmetologists','m_dir_uid'=>'278');
$m_dir_data[] = array('m_dir'=>'Costumes','m_dir_uid'=>'279');
$m_dir_data[] = array('m_dir'=>'Cotton','m_dir_uid'=>'280');
$m_dir_data[] = array('m_dir'=>'Counseling','m_dir_uid'=>'281');
$m_dir_data[] = array('m_dir'=>'Counter Tops','m_dir_uid'=>'282');
$m_dir_data[] = array('m_dir'=>'Coupons','m_dir_uid'=>'283');
$m_dir_data[] = array('m_dir'=>'Courier & Delivery','m_dir_uid'=>'284');
$m_dir_data[] = array('m_dir'=>'Court Reporters','m_dir_uid'=>'285');
$m_dir_data[] = array('m_dir'=>'CPR','m_dir_uid'=>'286');
$m_dir_data[] = array('m_dir'=>'Craft','m_dir_uid'=>'287');
$m_dir_data[] = array('m_dir'=>'Cranes','m_dir_uid'=>'288');
$m_dir_data[] = array('m_dir'=>'Crates & Crating','m_dir_uid'=>'289');
$m_dir_data[] = array('m_dir'=>'Credit Card','m_dir_uid'=>'290');
$m_dir_data[] = array('m_dir'=>'Credit Unions','m_dir_uid'=>'291');
$m_dir_data[] = array('m_dir'=>'Cremation','m_dir_uid'=>'292');
$m_dir_data[] = array('m_dir'=>'Crematories','m_dir_uid'=>'293');
$m_dir_data[] = array('m_dir'=>'Crop Dusting','m_dir_uid'=>'294');
$m_dir_data[] = array('m_dir'=>'Cruises','m_dir_uid'=>'295');
$m_dir_data[] = array('m_dir'=>'Currency Exchanges','m_dir_uid'=>'296');
$m_dir_data[] = array('m_dir'=>'Customs Brokers','m_dir_uid'=>'297');
$m_dir_data[] = array('m_dir'=>'Cutlery','m_dir_uid'=>'298');
$m_dir_data[] = array('m_dir'=>'Cylinders','m_dir_uid'=>'299');
$m_dir_data[] = array('m_dir'=>'Dairy Products','m_dir_uid'=>'300');
$m_dir_data[] = array('m_dir'=>'Dance','m_dir_uid'=>'301');
/*
$m_dir_data[] = array('m_dir'=>'','m_dir_uid'=>'');
$m_dir_data[] = array('m_dir'=>'','m_dir_uid'=>'');
$m_dir_data[] = array('m_dir'=>'','m_dir_uid'=>'');
$m_dir_data[] = array('m_dir'=>'','m_dir_uid'=>'');
$m_dir_data[] = array('m_dir'=>'','m_dir_uid'=>'');
$m_dir_data[] = array('m_dir'=>'','m_dir_uid'=>'');
*/

//$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'Certified Public','m_dir_uid'=>'1','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'1','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'2','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'2','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Materials','m_dir_uid'=>'2','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Musicians','m_dir_uid'=>'2','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Arial','m_dir_uid'=>'6','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Agencies & Consultants','m_dir_uid'=>'6','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Direct Mail','m_dir_uid'=>'6','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Directory & Guide','m_dir_uid'=>'6','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Internet','m_dir_uid'=>'6','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Newspaper','m_dir_uid'=>'6','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Outdoor','m_dir_uid'=>'6','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Promotional Products','m_dir_uid'=>'6','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Radio','m_dir_uid'=>'6','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Television','m_dir_uid'=>'6','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Buttons','m_dir_uid'=>'6','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'8','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'8','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Seeding & Spraying','m_dir_uid'=>'8','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Package Express','m_dir_uid'=>'9','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'9','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'10','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Systems','m_dir_uid'=>'10','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Repairing','m_dir_uid'=>'10','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Parts Wholesale','m_dir_uid'=>'10','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Mobile & Emergency Repair','m_dir_uid'=>'10','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Parts & Supplies','m_dir_uid'=>'10','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Systems Cleaning','m_dir_uid'=>'10','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Control Equipment','m_dir_uid'=>'12','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Service','m_dir_uid'=>'','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Cleaning Equipment','m_dir_uid'=>'13','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Service','m_dir_uid'=>'13','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Indoor','m_dir_uid'=>'14','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Outdoor','m_dir_uid'=>'14','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Avionics & Instruments','m_dir_uid'=>'15','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Charter & Leasing','m_dir_uid'=>'15','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Dealers & Sales','m_dir_uid'=>'15','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'15','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Flight Schools','m_dir_uid'=>'15','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Instructions','m_dir_uid'=>'15','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Servicing & Maintenance','m_dir_uid'=>'15','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Storage','m_dir_uid'=>'15','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Ticket Agencies','m_dir_uid'=>'17','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Parking','m_dir_uid'=>'18','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Transportation Services','m_dir_uid'=>'18','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Operations','m_dir_uid'=>'18','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Control Products','m_dir_uid'=>'20','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'20','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Health Practitioners','m_dir_uid'=>'22','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Pharmacies','m_dir_uid'=>'22','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Clinics','m_dir_uid'=>'22','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Fabricators','m_dir_uid'=>'24','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Recyclers','m_dir_uid'=>'24','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Sales','m_dir_uid'=>'25','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'25','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'25','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Sales','m_dir_uid'=>'26','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Reloading Equipment','m_dir_uid'=>'26','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'26','s_dir_uid'=>3);
$s_dir_data[] = array('s_dir'=>'Equipment','m_dir_uid'=>'27','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'27','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Parks','m_dir_uid'=>'27','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Places & Arcades','m_dir_uid'=>'27','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Hospitals','m_dir_uid'=>'28','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Rescue','m_dir_uid'=>'28','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Removal','m_dir_uid'=>'28','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Shelters','m_dir_uid'=>'28','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Support Services','m_dir_uid'=>'28','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Bureaus','m_dir_uid'=>'31','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'31','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'32','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Repairing & Restoration','m_dir_uid'=>'32','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Rental Information','m_dir_uid'=>'33','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Furnished','m_dir_uid'=>'33','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Unfurnished','m_dir_uid'=>'33','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Repair & Service','m_dir_uid'=>'34','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Sales','m_dir_uid'=>'34','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'34','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Parts & Supplies','m_dir_uid'=>'34','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Renting & Leasing','m_dir_uid'=>'34','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Used','m_dir_uid'=>'34','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'34','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Training Programs','m_dir_uid'=>'36','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Individuals','m_dir_uid'=>'36','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Schools','m_dir_uid'=>'36','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'37','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'37','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'38','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'38','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'41','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Ranges','m_dir_uid'=>'41','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Sales & Instruction','m_dir_uid'=>'41','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Builders','m_dir_uid'=>'42','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'42','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'42','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'43','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment','m_dir_uid'=>'43','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Sales','m_dir_uid'=>'43','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Service','m_dir_uid'=>'43','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Goods & Services','m_dir_uid'=>'44','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'44','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Recruiting','m_dir_uid'=>'44','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Goods & Services','m_dir_uid'=>'45','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'45','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Recruiting','m_dir_uid'=>'45','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Galleries','m_dir_uid'=>'47','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'47','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'47','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'47','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Schools','m_dir_uid'=>'47','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'47','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Restoration','m_dir_uid'=>'47','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Centers','m_dir_uid'=>'47','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Commercial','m_dir_uid'=>'52','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Fine Art','m_dir_uid'=>'52','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Removal','m_dir_uid'=>'53','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'53','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Abatement','m_dir_uid'=>'53','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'53','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Consulting & Testing','m_dir_uid'=>'53','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Inpection & Management','m_dir_uid'=>'53','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Paving','m_dir_uid'=>'54','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Sealcoating','m_dir_uid'=>'54','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'54','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Facilities','m_dir_uid'=>'56','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Products','m_dir_uid'=>'56','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'56','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Management','m_dir_uid'=>'57','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Criminal','m_dir_uid'=>'59','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Family','m_dir_uid'=>'59','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Divorce','m_dir_uid'=>'59','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Commercial','m_dir_uid'=>'59','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Collections','m_dir_uid'=>'59','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Bail Bonds','m_dir_uid'=>'59','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Immigration','m_dir_uid'=>'59','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Personal Injury','m_dir_uid'=>'59','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Wrongful Death','m_dir_uid'=>'59','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Car Wrecks','m_dir_uid'=>'59','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Jail Release','m_dir_uid'=>'59','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Bankruptcy','m_dir_uid'=>'59','s_dir_uid'=>'12');
$s_dir_data[] = array('s_dir'=>'Accidents','m_dir_uid'=>'59','s_dir_uid'=>'13');
$s_dir_data[] = array('s_dir'=>'Social Security','m_dir_uid'=>'59','s_dir_uid'=>'14');
$s_dir_data[] = array('s_dir'=>'Disability','m_dir_uid'=>'59','s_dir_uid'=>'15');
$s_dir_data[] = array('s_dir'=>'Employee Rights','m_dir_uid'=>'59','s_dir_uid'=>'16');
$s_dir_data[] = array('s_dir'=>'DWI','m_dir_uid'=>'59','s_dir_uid'=>'17');
$s_dir_data[] = array('s_dir'=>'DUI','m_dir_uid'=>'59','s_dir_uid'=>'18');
$s_dir_data[] = array('s_dir'=>'Estate Planning','m_dir_uid'=>'59','s_dir_uid'=>'19');
$s_dir_data[] = array('s_dir'=>'Farm & Ranch','m_dir_uid'=>'59','s_dir_uid'=>'20');
$s_dir_data[] = array('s_dir'=>'Real Estate','m_dir_uid'=>'59','s_dir_uid'=>'21');
$s_dir_data[] = array('s_dir'=>'Juvenile','m_dir_uid'=>'59','s_dir_uid'=>'22');
$s_dir_data[] = array('s_dir'=>'Employment','m_dir_uid'=>'59','s_dir_uid'=>'23');
$s_dir_data[] = array('s_dir'=>'Gas & Mineral','m_dir_uid'=>'59','s_dir_uid'=>'24');
$s_dir_data[] = array('s_dir'=>'Tax Law','m_dir_uid'=>'59','s_dir_uid'=>'25');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'59','s_dir_uid'=>'26');
$s_dir_data[] = array('s_dir'=>'Service Bureaus','m_dir_uid'=>'59','s_dir_uid'=>'27');
$s_dir_data[] = array('s_dir'=>'Houses','m_dir_uid'=>'61','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Auctioneers','m_dir_uid'=>'61','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Advertising','m_dir_uid'=>'62','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Video Consultants','m_dir_uid'=>'62','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Video Equipment','m_dir_uid'=>'62','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Renting & Leasing','m_dir_uid'=>'62','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Service & Repair','m_dir_uid'=>'62','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'62','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Video Production Services','m_dir_uid'=>'62','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Accessories','m_dir_uid'=>'63','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Air Conditioning','m_dir_uid'=>'63','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Alarm & Security','m_dir_uid'=>'63','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Antique & Classic','m_dir_uid'=>'63','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Appraising Services','m_dir_uid'=>'63','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Auctions','m_dir_uid'=>'63','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Body Paint & Repair','m_dir_uid'=>'63','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'63','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Bumpers & Grills','m_dir_uid'=>'63','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Customizing','m_dir_uid'=>'63','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Dealers - New','m_dir_uid'=>'63','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Dealers - Used','m_dir_uid'=>'63','s_dir_uid'=>'12');
$s_dir_data[] = array('s_dir'=>'Paintless Dent Repair','m_dir_uid'=>'63','s_dir_uid'=>'13');
$s_dir_data[] = array('s_dir'=>'Detailing','m_dir_uid'=>'63','s_dir_uid'=>'14');
$s_dir_data[] = array('s_dir'=>'Electric Equipment','m_dir_uid'=>'63','s_dir_uid'=>'15');
$s_dir_data[] = array('s_dir'=>'Electric Services','m_dir_uid'=>'63','s_dir_uid'=>'16');
$s_dir_data[] = array('s_dir'=>'Emission Testing','m_dir_uid'=>'63','s_dir_uid'=>'17');
$s_dir_data[] = array('s_dir'=>'Engine Rebuilding','m_dir_uid'=>'63','s_dir_uid'=>'18');
$s_dir_data[] = array('s_dir'=>'Engines','m_dir_uid'=>'63','s_dir_uid'=>'19');
$s_dir_data[] = array('s_dir'=>'Information Services','m_dir_uid'=>'63','s_dir_uid'=>'20');
$s_dir_data[] = array('s_dir'=>'Unlocking Assistance','m_dir_uid'=>'63','s_dir_uid'=>'21');
$s_dir_data[] = array('s_dir'=>'Machine Shop Services','m_dir_uid'=>'63','s_dir_uid'=>'22');
$s_dir_data[] = array('s_dir'=>'Oil & Lube','m_dir_uid'=>'63','s_dir_uid'=>'23');
$s_dir_data[] = array('s_dir'=>'Parts & Supplies - new','m_dir_uid'=>'63','s_dir_uid'=>'24');
$s_dir_data[] = array('s_dir'=>'Parts & Supplies - used','m_dir_uid'=>'63','s_dir_uid'=>'25');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'63','s_dir_uid'=>'26');
$s_dir_data[] = array('s_dir'=>'Performance & Racing','m_dir_uid'=>'63','s_dir_uid'=>'27');
$s_dir_data[] = array('s_dir'=>'Racing','m_dir_uid'=>'63','s_dir_uid'=>'28');
$s_dir_data[] = array('s_dir'=>'Stereo Systems','m_dir_uid'=>'63','s_dir_uid'=>'29');
$s_dir_data[] = array('s_dir'=>'Renting','m_dir_uid'=>'63','s_dir_uid'=>'30');
$s_dir_data[] = array('s_dir'=>'Repair & Service','m_dir_uid'=>'63','s_dir_uid'=>'31');
$s_dir_data[] = array('s_dir'=>'Tops & Upholstery','m_dir_uid'=>'63','s_dir_uid'=>'32');
$s_dir_data[] = array('s_dir'=>'Smog Testing','m_dir_uid'=>'63','s_dir_uid'=>'33');
$s_dir_data[] = array('s_dir'=>'Storage','m_dir_uid'=>'63','s_dir_uid'=>'34');
$s_dir_data[] = array('s_dir'=>'Sunroofs','m_dir_uid'=>'63','s_dir_uid'=>'35');
$s_dir_data[] = array('s_dir'=>'Transporters','m_dir_uid'=>'63','s_dir_uid'=>'36');
$s_dir_data[] = array('s_dir'=>'Buyers & Brokers','m_dir_uid'=>'63','s_dir_uid'=>'37');
$s_dir_data[] = array('s_dir'=>'Inspection Services','m_dir_uid'=>'63','s_dir_uid'=>'38');
$s_dir_data[] = array('s_dir'=>'Warranty Services','m_dir_uid'=>'63','s_dir_uid'=>'39');
$s_dir_data[] = array('s_dir'=>'Wreckers','m_dir_uid'=>'63','s_dir_uid'=>'40');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'67','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Repair & Service','m_dir_uid'=>'67','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Accessories','m_dir_uid'=>'68','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'General','m_dir_uid'=>'68','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Furnishings','m_dir_uid'=>'68','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Prevention Devices','m_dir_uid'=>'69','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'General Services','m_dir_uid'=>'69','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Paper','m_dir_uid'=>'73','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Plastic','m_dir_uid'=>'73','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Specialty','m_dir_uid'=>'73','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'75','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Retail','m_dir_uid'=>'75','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'75','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Arrangements','m_dir_uid'=>'77','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Retail','m_dir_uid'=>'77','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Delivery','m_dir_uid'=>'77','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Decorators','m_dir_uid'=>'77','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Rides','m_dir_uid'=>'77','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Advertising','m_dir_uid'=>'77','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'80','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Designers','m_dir_uid'=>'80','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'80','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Advertising','m_dir_uid'=>'83','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Specialty','m_dir_uid'=>'83','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Flags & Pennants','m_dir_uid'=>'83','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Halls','m_dir_uid'=>'84','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Reception Facilities','m_dir_uid'=>'84','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Scanning Equipment','m_dir_uid'=>'85','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Sales & Service','m_dir_uid'=>'85','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'85','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Establishments','m_dir_uid'=>'86','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment','m_dir_uid'=>'86','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'86','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Vendors','m_dir_uid'=>'86','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Restaurants','m_dir_uid'=>'87','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'87','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Corporate','m_dir_uid'=>'87','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Vendors','m_dir_uid'=>'87','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Schools','m_dir_uid'=>'88','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Barbers','m_dir_uid'=>'88','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'88','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Schools','m_dir_uid'=>'91','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Organizations','m_dir_uid'=>'91','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Fields & Cages','m_dir_uid'=>'92','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'92','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Organizations','m_dir_uid'=>'92','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Courts','m_dir_uid'=>'93','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Construction','m_dir_uid'=>'93','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'93','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Organizations','m_dir_uid'=>'93','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Fixtures','m_dir_uid'=>'94','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Cabinets & Accessories','m_dir_uid'=>'94','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'94','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Remodeling','m_dir_uid'=>'94','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Baths','m_dir_uid'=>'94','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Construction','m_dir_uid'=>'95','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Contractor','m_dir_uid'=>'95','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'95','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Repair & Refinish','m_dir_uid'=>'96','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'96','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'96','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Repairing','m_dir_uid'=>'97','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Rebuilding','m_dir_uid'=>'97','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Recharging','m_dir_uid'=>'97','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Recycling','m_dir_uid'=>'97','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Storage','m_dir_uid'=>'97','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'97','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'97','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Salons','m_dir_uid'=>'100','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'100','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies Wholesale','m_dir_uid'=>'100','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'100','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Schools & Colleges','m_dir_uid'=>'100','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'102','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Supplies & Equipment','m_dir_uid'=>'102','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'102','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Linens & Bedding','m_dir_uid'=>'102','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Control & Removal','m_dir_uid'=>'103','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Honey Farms','m_dir_uid'=>'103','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies & Equipment','m_dir_uid'=>'103','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Taverns','m_dir_uid'=>'104','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Distributors','m_dir_uid'=>'104','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Homebrewing','m_dir_uid'=>'104','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'104','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Dispensing','m_dir_uid'=>'105','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'105','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Retail','m_dir_uid'=>'105','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Soft Drinks','m_dir_uid'=>'105','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Juices','m_dir_uid'=>'105','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Mixers','m_dir_uid'=>'105','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Distributors','m_dir_uid'=>'105','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Bottlers','m_dir_uid'=>'105','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Schools','m_dir_uid'=>'106','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Churches','m_dir_uid'=>'106','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'106','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'106','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'107','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Racks','m_dir_uid'=>'107','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Security Systems','m_dir_uid'=>'107','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Renting','m_dir_uid'=>'107','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'107','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'107','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'107','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'109','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Parlors','m_dir_uid'=>'109','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Sales & Service','m_dir_uid'=>'109','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Loose Leaf','m_dir_uid'=>'111','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Magazine','m_dir_uid'=>'111','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'111','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Halls','m_dir_uid'=>'112','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment','m_dir_uid'=>'112','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'112','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Schools','m_dir_uid'=>'115','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'115','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Colleges','m_dir_uid'=>'115','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Barriers','m_dir_uid'=>'116','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Repellants','m_dir_uid'=>'116','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Controls','m_dir_uid'=>'116','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Feeders','m_dir_uid'=>'116','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Houses & Seed','m_dir_uid'=>'116','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Training','m_dir_uid'=>'116','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Control','m_dir_uid'=>'117','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Information','m_dir_uid'=>'117','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'117','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Parenting Centers','m_dir_uid'=>'117','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Education','m_dir_uid'=>'117','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Parties','m_dir_uid'=>'118','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'118','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Rentals','m_dir_uid'=>'118','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Equipment','m_dir_uid'=>'118','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'119','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'119','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Companies','m_dir_uid'=>'119','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Vision Impaired','m_dir_uid'=>'120','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Services','m_dir_uid'=>'120','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Schools','m_dir_uid'=>'120','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Venetian','m_dir_uid'=>'121','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Mini','m_dir_uid'=>'121','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Vertical','m_dir_uid'=>'121','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Wood','m_dir_uid'=>'121','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'121','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'121','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'121','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Builders','m_dir_uid'=>'127','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Yards','m_dir_uid'=>'127','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Charters','m_dir_uid'=>'127','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Cleaning & Detailing','m_dir_uid'=>'127','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Covers','m_dir_uid'=>'127','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Upholstery','m_dir_uid'=>'127','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'127','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'127','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Docks','m_dir_uid'=>'127','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'127','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Lifts','m_dir_uid'=>'127','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Propellers','m_dir_uid'=>'127','s_dir_uid'=>'12');
$s_dir_data[] = array('s_dir'=>'Renting & Leasing','m_dir_uid'=>'127','s_dir_uid'=>'13');
$s_dir_data[] = array('s_dir'=>'Repairing','m_dir_uid'=>'127','s_dir_uid'=>'14');
$s_dir_data[] = array('s_dir'=>'Maintenance','m_dir_uid'=>'127','s_dir_uid'=>'15');
$s_dir_data[] = array('s_dir'=>'Storage','m_dir_uid'=>'127','s_dir_uid'=>'16');
$s_dir_data[] = array('s_dir'=>'Distributors','m_dir_uid'=>'129','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'129','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Repairing & Cleaning','m_dir_uid'=>'129','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Dealers New','m_dir_uid'=>'132','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Dealers Used','m_dir_uid'=>'132','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Development','m_dir_uid'=>'132','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Binders','m_dir_uid'=>'132','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'132','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Business','m_dir_uid'=>'133','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Personal','m_dir_uid'=>'133','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'134','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Retail','m_dir_uid'=>'134','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'134','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'135','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Supplies & Equipment','m_dir_uid'=>'135','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'138','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'138','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'141','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'141','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Service','m_dir_uid'=>'141','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Layers','m_dir_uid'=>'145','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Supplies & Equipment','m_dir_uid'=>'145','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Gown Preservation','m_dir_uid'=>'146','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Shops','m_dir_uid'=>'146','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'146','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'146','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'146','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Hardware','m_dir_uid'=>'151','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Cleaning Interior','m_dir_uid'=>'151','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Cleaning Exterior','m_dir_uid'=>'151','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Construction','m_dir_uid'=>'151','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'151','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Designers','m_dir_uid'=>'151','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'151','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Maintenance','m_dir_uid'=>'151','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Materials New','m_dir_uid'=>'151','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Materials Used','m_dir_uid'=>'151','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'151','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'151','s_dir_uid'=>'12');
$s_dir_data[] = array('s_dir'=>'Restoration','m_dir_uid'=>'151','s_dir_uid'=>'13');
$s_dir_data[] = array('s_dir'=>'Metal','m_dir_uid'=>'151','s_dir_uid'=>'14');
$s_dir_data[] = array('s_dir'=>'Portable','m_dir_uid'=>'151','s_dir_uid'=>'15');
$s_dir_data[] = array('s_dir'=>'Prefabricated','m_dir_uid'=>'151','s_dir_uid'=>'16');
$s_dir_data[] = array('s_dir'=>'Charters','m_dir_uid'=>'155','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Rentals','m_dir_uid'=>'155','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Lines','m_dir_uid'=>'155','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Sales','m_dir_uid'=>'155','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'155','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'155','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Brokers','m_dir_uid'=>'156','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Coaches','m_dir_uid'=>'156','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'156','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Development','m_dir_uid'=>'156','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Forms','m_dir_uid'=>'156','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'System','m_dir_uid'=>'156','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Management','m_dir_uid'=>'156','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Trade Organizations','m_dir_uid'=>'156','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Makers','m_dir_uid'=>'158','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Refinishing','m_dir_uid'=>'158','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'158','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Equiment & Supplies','m_dir_uid'=>'158','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Television','m_dir_uid'=>'160','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Satellite','m_dir_uid'=>'160','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'160','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'161','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Companies','m_dir_uid'=>'161','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'161','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Decorating','m_dir_uid'=>'164','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Bakers','m_dir_uid'=>'164','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'164','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Education & Support','m_dir_uid'=>'174','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Treatment Centers','m_dir_uid'=>'174','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Kayaks','m_dir_uid'=>'178','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Rentals','m_dir_uid'=>'178','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Trips','m_dir_uid'=>'178','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Locations','m_dir_uid'=>'182','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'182','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'186','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Cleaners','m_dir_uid'=>'188','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment Rental','m_dir_uid'=>'188','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equiment & Supplies','m_dir_uid'=>'188','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Water Extraction','m_dir_uid'=>'188','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'188','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'188','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Restoration','m_dir_uid'=>'188','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Binding','m_dir_uid'=>'188','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Dyers','m_dir_uid'=>'188','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Installers','m_dir_uid'=>'188','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Repairing','m_dir_uid'=>'188','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'191','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Vendors','m_dir_uid'=>'191','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'191','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'195','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'195','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'198','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'198','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Sales & Service','m_dir_uid'=>'198','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'198','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'199','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'199','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'200','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'201','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Products','m_dir_uid'=>'201','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Rentals','m_dir_uid'=>'203','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Builders & Repair','m_dir_uid'=>'216','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Fireplace Cleaning','m_dir_uid'=>'216','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Lights & Decorations','m_dir_uid'=>'222','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Trees','m_dir_uid'=>'222','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Advent Christian','m_dir_uid'=>'224','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'African Methodist','m_dir_uid'=>'224','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Angelican','m_dir_uid'=>'224','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Apostolic','m_dir_uid'=>'224','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Assemblies of God','m_dir_uid'=>'224','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Baptist','m_dir_uid'=>'224','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Baptist Southern','m_dir_uid'=>'224','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Bible','m_dir_uid'=>'224','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Brethren','m_dir_uid'=>'224','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Buddhist','m_dir_uid'=>'224','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Catholic','m_dir_uid'=>'224','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Charismatic','m_dir_uid'=>'224','s_dir_uid'=>'12');
$s_dir_data[] = array('s_dir'=>'Chinese','m_dir_uid'=>'224','s_dir_uid'=>'13');
$s_dir_data[] = array('s_dir'=>'Christian','m_dir_uid'=>'224','s_dir_uid'=>'14');
$s_dir_data[] = array('s_dir'=>'Disciples of Christ','m_dir_uid'=>'224','s_dir_uid'=>'15');
$s_dir_data[] = array('s_dir'=>'Christian Independant','m_dir_uid'=>'224','s_dir_uid'=>'16');
$s_dir_data[] = array('s_dir'=>'Church of Christ','m_dir_uid'=>'224','s_dir_uid'=>'17');
$s_dir_data[] = array('s_dir'=>'Church of God In Christ','m_dir_uid'=>'224','s_dir_uid'=>'18');
$s_dir_data[] = array('s_dir'=>'Church of God Of Prophecy','m_dir_uid'=>'224','s_dir_uid'=>'19');
$s_dir_data[] = array('s_dir'=>'Church of Jesus Christ LDS','m_dir_uid'=>'224','s_dir_uid'=>'20');
$s_dir_data[] = array('s_dir'=>'Church of the Nazarene','m_dir_uid'=>'224','s_dir_uid'=>'21');
$s_dir_data[] = array('s_dir'=>'Covenant','m_dir_uid'=>'224','s_dir_uid'=>'22');
$s_dir_data[] = array('s_dir'=>'Eastern Orthodox','m_dir_uid'=>'224','s_dir_uid'=>'23');
$s_dir_data[] = array('s_dir'=>'Episcopal','m_dir_uid'=>'224','s_dir_uid'=>'24');
$s_dir_data[] = array('s_dir'=>'Evangelical','m_dir_uid'=>'224','s_dir_uid'=>'25');
$s_dir_data[] = array('s_dir'=>'Greek Orthodox','m_dir_uid'=>'224','s_dir_uid'=>'26');
$s_dir_data[] = array('s_dir'=>'Hindu','m_dir_uid'=>'224','s_dir_uid'=>'27');
$s_dir_data[] = array('s_dir'=>'Hispanic','m_dir_uid'=>'224','s_dir_uid'=>'28');
$s_dir_data[] = array('s_dir'=>'Islam','m_dir_uid'=>'224','s_dir_uid'=>'29');
$s_dir_data[] = array('s_dir'=>'Jehovah\'s Witnesses','m_dir_uid'=>'224','s_dir_uid'=>'30');
$s_dir_data[] = array('s_dir'=>'Korean','m_dir_uid'=>'224','s_dir_uid'=>'31');
$s_dir_data[] = array('s_dir'=>'Lutheran','m_dir_uid'=>'224','s_dir_uid'=>'32');
$s_dir_data[] = array('s_dir'=>'Mennonite','m_dir_uid'=>'224','s_dir_uid'=>'33');
$s_dir_data[] = array('s_dir'=>'Methodist','m_dir_uid'=>'224','s_dir_uid'=>'34');
$s_dir_data[] = array('s_dir'=>'Missionary','m_dir_uid'=>'224','s_dir_uid'=>'35');
$s_dir_data[] = array('s_dir'=>'Non_Denominational','m_dir_uid'=>'224','s_dir_uid'=>'36');
$s_dir_data[] = array('s_dir'=>'Orthodox','m_dir_uid'=>'224','s_dir_uid'=>'37');
$s_dir_data[] = array('s_dir'=>'Pagan','m_dir_uid'=>'224','s_dir_uid'=>'38');
$s_dir_data[] = array('s_dir'=>'Pentecostal','m_dir_uid'=>'224','s_dir_uid'=>'39');
$s_dir_data[] = array('s_dir'=>'Presbyterian','m_dir_uid'=>'224','s_dir_uid'=>'40');
$s_dir_data[] = array('s_dir'=>'Roman Catholic','m_dir_uid'=>'224','s_dir_uid'=>'41');
$s_dir_data[] = array('s_dir'=>'Sabbatarian','m_dir_uid'=>'224','s_dir_uid'=>'42');
$s_dir_data[] = array('s_dir'=>'Scientology','m_dir_uid'=>'224','s_dir_uid'=>'43');
$s_dir_data[] = array('s_dir'=>'Seventh Day Adventist','m_dir_uid'=>'224','s_dir_uid'=>'44');
$s_dir_data[] = array('s_dir'=>'Spiritualist','m_dir_uid'=>'224','s_dir_uid'=>'45');
$s_dir_data[] = array('s_dir'=>'Unitarian','m_dir_uid'=>'224','s_dir_uid'=>'46');
$s_dir_data[] = array('s_dir'=>'United Church of Christ','m_dir_uid'=>'224','s_dir_uid'=>'47');
$s_dir_data[] = array('s_dir'=>'United Methodist','m_dir_uid'=>'224','s_dir_uid'=>'48');
$s_dir_data[] = array('s_dir'=>'Wesleyan','m_dir_uid'=>'224','s_dir_uid'=>'49');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'227','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Industrial','m_dir_uid'=>'227','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Chiropractic','m_dir_uid'=>'228','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Dental','m_dir_uid'=>'228','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Fertility','m_dir_uid'=>'228','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Health & Walfare','m_dir_uid'=>'228','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Medical','m_dir_uid'=>'228','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Osteopathic','m_dir_uid'=>'228','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Pain','m_dir_uid'=>'228','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Podiatry','m_dir_uid'=>'228','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Psychiatric','m_dir_uid'=>'228','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Service & Repair','m_dir_uid'=>'229','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Accessories','m_dir_uid'=>'231','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Design & Remodeling','m_dir_uid'=>'231','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Vintage & Collectible','m_dir_uid'=>'232','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Adaptive','m_dir_uid'=>'232','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Custom Made','m_dir_uid'=>'232','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Printing & Lettering','m_dir_uid'=>'232','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Resale','m_dir_uid'=>'232','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Retail','m_dir_uid'=>'232','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'232','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'232','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Womens','m_dir_uid'=>'232','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Mens','m_dir_uid'=>'232','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Juniors','m_dir_uid'=>'232','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Childrens','m_dir_uid'=>'232','s_dir_uid'=>'12');
$s_dir_data[] = array('s_dir'=>'Baby & Infant','m_dir_uid'=>'232','s_dir_uid'=>'13');
$s_dir_data[] = array('s_dir'=>'Houses','m_dir_uid'=>'239','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'239','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Brewing','m_dir_uid'=>'239','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Roasting','m_dir_uid'=>'239','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Tea','m_dir_uid'=>'239','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Sorting Machines','m_dir_uid'=>'240','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Dealers & Supplies','m_dir_uid'=>'240','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Admission Planners','m_dir_uid'=>'244','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Fund Planning','m_dir_uid'=>'244','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Universities','m_dir_uid'=>'244','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'248','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'248','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'248','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Equipment & Repair','m_dir_uid'=>'248','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Rental','m_dir_uid'=>'253','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Service & Repair','m_dir_uid'=>'253','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Administration','m_dir_uid'=>'254','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Cable & Wire','m_dir_uid'=>'254','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Sales New','m_dir_uid'=>'254','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Sales Used','m_dir_uid'=>'254','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Industrial','m_dir_uid'=>'254','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Business','m_dir_uid'=>'254','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Rental & Lease','m_dir_uid'=>'254','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Repair & Service','m_dir_uid'=>'254','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Supplies & Parts','m_dir_uid'=>'254','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Wholesale','m_dir_uid'=>'254','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Manufacturers','m_dir_uid'=>'254','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Data Recovery','m_dir_uid'=>'254','s_dir_uid'=>'12');
$s_dir_data[] = array('s_dir'=>'Forensics','m_dir_uid'=>'254','s_dir_uid'=>'13');
$s_dir_data[] = array('s_dir'=>'Graphics & Digital Design','m_dir_uid'=>'254','s_dir_uid'=>'14');
$s_dir_data[] = array('s_dir'=>'Network Design','m_dir_uid'=>'254','s_dir_uid'=>'15');
$s_dir_data[] = array('s_dir'=>'Online Services','m_dir_uid'=>'254','s_dir_uid'=>'16');
$s_dir_data[] = array('s_dir'=>'E-Commerce','m_dir_uid'=>'254','s_dir_uid'=>'17');
$s_dir_data[] = array('s_dir'=>'Printers & Ink','m_dir_uid'=>'254','s_dir_uid'=>'18');
$s_dir_data[] = array('s_dir'=>'Projectors','m_dir_uid'=>'254','s_dir_uid'=>'19');
$s_dir_data[] = array('s_dir'=>'Recycling','m_dir_uid'=>'254','s_dir_uid'=>'20');
$s_dir_data[] = array('s_dir'=>'Cleanrooms','m_dir_uid'=>'254','s_dir_uid'=>'21');
$s_dir_data[] = array('s_dir'=>'Security','m_dir_uid'=>'254','s_dir_uid'=>'22');
$s_dir_data[] = array('s_dir'=>'Software','m_dir_uid'=>'254','s_dir_uid'=>'23');
$s_dir_data[] = array('s_dir'=>'System Designers','m_dir_uid'=>'254','s_dir_uid'=>'24');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'254','s_dir_uid'=>'25');
$s_dir_data[] = array('s_dir'=>'Technical Assistance','m_dir_uid'=>'254','s_dir_uid'=>'26');
$s_dir_data[] = array('s_dir'=>'Support','m_dir_uid'=>'254','s_dir_uid'=>'27');
$s_dir_data[] = array('s_dir'=>'Training','m_dir_uid'=>'254','s_dir_uid'=>'28');
$s_dir_data[] = array('s_dir'=>'Halls & Venues','m_dir_uid'=>'255','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Vendors','m_dir_uid'=>'256','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'256','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Additives','m_dir_uid'=>'257','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Aggregates','m_dir_uid'=>'257','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Blocks & Shapes','m_dir_uid'=>'257','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Coating','m_dir_uid'=>'257','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'257','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Cutting & Sawing','m_dir_uid'=>'257','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Curing & Treating','m_dir_uid'=>'257','s_dir_uid'=>'7');
$s_dir_data[] = array('s_dir'=>'Decorative & Stamped','m_dir_uid'=>'257','s_dir_uid'=>'8');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'257','s_dir_uid'=>'9');
$s_dir_data[] = array('s_dir'=>'Mixers','m_dir_uid'=>'257','s_dir_uid'=>'10');
$s_dir_data[] = array('s_dir'=>'Pumping','m_dir_uid'=>'257','s_dir_uid'=>'11');
$s_dir_data[] = array('s_dir'=>'Reinforcements','m_dir_uid'=>'257','s_dir_uid'=>'12');
$s_dir_data[] = array('s_dir'=>'Stain & Sealer','m_dir_uid'=>'257','s_dir_uid'=>'13');
$s_dir_data[] = array('s_dir'=>'Management','m_dir_uid'=>'259','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment','m_dir_uid'=>'262','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Contractors','m_dir_uid'=>'262','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Clean Up','m_dir_uid'=>'262','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Consultants','m_dir_uid'=>'262','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Estimates','m_dir_uid'=>'262','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Management','m_dir_uid'=>'262','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Brokers','m_dir_uid'=>'263','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Referral Services','m_dir_uid'=>'263','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Remodeling','m_dir_uid'=>'266','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'Rentals','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'General','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'Systems & Regulators','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'Make-Up','m_dir_uid'=>'277','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Plastic Surgery','m_dir_uid'=>'277','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Services','m_dir_uid'=>'277','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Perfumes','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'Buyers','m_dir_uid'=>'280','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Compresses','m_dir_uid'=>'280','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Gins','m_dir_uid'=>'280','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Oil Mills','m_dir_uid'=>'280','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Galleries','m_dir_uid'=>'287','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Dealers','m_dir_uid'=>'287','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Supplies','m_dir_uid'=>'287','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Hoisting & Rigging','m_dir_uid'=>'288','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Inspection & Testing','m_dir_uid'=>'288','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Mobile','m_dir_uid'=>'288','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Parts & Service','m_dir_uid'=>'288','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Renting & Leasing','m_dir_uid'=>'288','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'288','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Merchant Providers','m_dir_uid'=>'290','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Credit Plans','m_dir_uid'=>'290','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Equipment & Supplies','m_dir_uid'=>'290','s_dir_uid'=>'3');
$s_dir_data[] = array('s_dir'=>'Debt Counseling','m_dir_uid'=>'290','s_dir_uid'=>'4');
$s_dir_data[] = array('s_dir'=>'Repair','m_dir_uid'=>'290','s_dir_uid'=>'5');
$s_dir_data[] = array('s_dir'=>'Reporting Agencies','m_dir_uid'=>'290','s_dir_uid'=>'6');
$s_dir_data[] = array('s_dir'=>'Schools','m_dir_uid'=>'301','s_dir_uid'=>'1');
$s_dir_data[] = array('s_dir'=>'Apparel & Supplies','m_dir_uid'=>'301','s_dir_uid'=>'2');
$s_dir_data[] = array('s_dir'=>'Instruction','m_dir_uid'=>'301','s_dir_uid'=>'3');
/*
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
$s_dir_data[] = array('s_dir'=>'','m_dir_uid'=>'','s_dir_uid'=>'');
*/

$f_dir_data[] = array();
?>
