<?php 
//$m_cat_data[] = array('m_cat'=>'','m_cat_uid'=>'');
$m_cat_data[] = array('m_cat'=>'For Sale','m_cat_uid'=>'1');
$m_cat_data[] = array('m_cat'=>'Housing','m_cat_uid'=>'2');
$m_cat_data[] = array('m_cat'=>'Jobs','m_cat_uid'=>'3');
$m_cat_data[] = array('m_cat'=>'Personals','m_cat_uid'=>'4');
$m_cat_data[] = array('m_cat'=>'Services','m_cat_uid'=>'5');

//$s_cat_data[] = array('s_cat'=>'','m_cat_uid'=>'','s_cat_uid'=>'');
$s_cat_data[] = array('s_cat'=>'Antiques','m_cat_uid'=>'1','s_cat_uid'=>'1');
$s_cat_data[] = array('s_cat'=>'Appliances','m_cat_uid'=>'1','s_cat_uid'=>'2');
$s_cat_data[] = array('s_cat'=>'Arts & Crafts','m_cat_uid'=>'1','s_cat_uid'=>'3');
$s_cat_data[] = array('s_cat'=>'Automotive','m_cat_uid'=>'1','s_cat_uid'=>'4');
$s_cat_data[] = array('s_cat'=>'Aviation','m_cat_uid'=>'1','s_cat_uid'=>'5');
$s_cat_data[] = array('s_cat'=>'Barter','m_cat_uid'=>'1','s_cat_uid'=>'6');
$s_cat_data[] = array('s_cat'=>'Bicycles','m_cat_uid'=>'1','s_cat_uid'=>'7');
$s_cat_data[] = array('s_cat'=>'Boats','m_cat_uid'=>'1','s_cat_uid'=>'8');
$s_cat_data[] = array('s_cat'=>'Books','m_cat_uid'=>'1','s_cat_uid'=>'9');
$s_cat_data[] = array('s_cat'=>'Business','m_cat_uid'=>'1','s_cat_uid'=>'10');
$s_cat_data[] = array('s_cat'=>'Cars','m_cat_uid'=>'1','s_cat_uid'=>'11');
$s_cat_data[] = array('s_cat'=>'DVD\'s & Blue Ray','m_cat_uid'=>'1','s_cat_uid'=>'12');
$s_cat_data[] = array('s_cat'=>'CD\'s & Vinyl','m_cat_uid'=>'1','s_cat_uid'=>'55');
$s_cat_data[] = array('s_cat'=>'VHS & Laser Disc','m_cat_uid'=>'1','s_cat_uid'=>'56');
$s_cat_data[] = array('s_cat'=>'Cell Phones','m_cat_uid'=>'1','s_cat_uid'=>'13');
$s_cat_data[] = array('s_cat'=>'Childrens','m_cat_uid'=>'1','s_cat_uid'=>'14');
$s_cat_data[] = array('s_cat'=>'Collectibles','m_cat_uid'=>'1','s_cat_uid'=>'15');
$s_cat_data[] = array('s_cat'=>'Computers','m_cat_uid'=>'1','s_cat_uid'=>'16');
$s_cat_data[] = array('s_cat'=>'Digital Downloads','m_cat_uid'=>'1','s_cat_uid'=>'17');
$s_cat_data[] = array('s_cat'=>'Ebooks','m_cat_uid'=>'1','s_cat_uid'=>'18');
$s_cat_data[] = array('s_cat'=>'Electronics','m_cat_uid'=>'1','s_cat_uid'=>'19');
$s_cat_data[] = array('s_cat'=>'Entertainment','m_cat_uid'=>'1','s_cat_uid'=>'20');
$s_cat_data[] = array('s_cat'=>'Exercise Equipment','m_cat_uid'=>'1','s_cat_uid'=>'21');
$s_cat_data[] = array('s_cat'=>'Farming & Ranch','m_cat_uid'=>'1','s_cat_uid'=>'22');
$s_cat_data[] = array('s_cat'=>'Firearms','m_cat_uid'=>'1','s_cat_uid'=>'23');
$s_cat_data[] = array('s_cat'=>'Free','m_cat_uid'=>'1','s_cat_uid'=>'24');
$s_cat_data[] = array('s_cat'=>'Furniture','m_cat_uid'=>'1','s_cat_uid'=>'25');
$s_cat_data[] = array('s_cat'=>'Games & Video Games','m_cat_uid'=>'1','s_cat_uid'=>'26');
$s_cat_data[] = array('s_cat'=>'Gardening & Landscaping','m_cat_uid'=>'1','s_cat_uid'=>'27');
$s_cat_data[] = array('s_cat'=>'General & Misc','m_cat_uid'=>'1','s_cat_uid'=>'28');
$s_cat_data[] = array('s_cat'=>'Health & Beauty','m_cat_uid'=>'1','s_cat_uid'=>'29');
$s_cat_data[] = array('s_cat'=>'Heavy Machinery','m_cat_uid'=>'1','s_cat_uid'=>'30');
$s_cat_data[] = array('s_cat'=>'Household','m_cat_uid'=>'1','s_cat_uid'=>'31');
$s_cat_data[] = array('s_cat'=>'Jewelry','m_cat_uid'=>'1','s_cat_uid'=>'32');
$s_cat_data[] = array('s_cat'=>'Lawn Mowers','m_cat_uid'=>'1','s_cat_uid'=>'33');
$s_cat_data[] = array('s_cat'=>'Literature','m_cat_uid'=>'1','s_cat_uid'=>'34');
$s_cat_data[] = array('s_cat'=>'Materials','m_cat_uid'=>'1','s_cat_uid'=>'35');
$s_cat_data[] = array('s_cat'=>'Mens','m_cat_uid'=>'1','s_cat_uid'=>'36');
$s_cat_data[] = array('s_cat'=>'Motorcycles','m_cat_uid'=>'1','s_cat_uid'=>'37');
$s_cat_data[] = array('s_cat'=>'Musical Instruments','m_cat_uid'=>'1','s_cat_uid'=>'38');
$s_cat_data[] = array('s_cat'=>'Outdoor Recreation','m_cat_uid'=>'1','s_cat_uid'=>'39');
$s_cat_data[] = array('s_cat'=>'Outdoor Sporting','m_cat_uid'=>'1','s_cat_uid'=>'40');
$s_cat_data[] = array('s_cat'=>'Pets','m_cat_uid'=>'1','s_cat_uid'=>'41');
$s_cat_data[] = array('s_cat'=>'Photography','m_cat_uid'=>'1','s_cat_uid'=>'42');
$s_cat_data[] = array('s_cat'=>'Residential','m_cat_uid'=>'1','s_cat_uid'=>'43');
$s_cat_data[] = array('s_cat'=>'RV\'s','m_cat_uid'=>'1','s_cat_uid'=>'44');
$s_cat_data[] = array('s_cat'=>'Software','m_cat_uid'=>'1','s_cat_uid'=>'45');
$s_cat_data[] = array('s_cat'=>'Sporting Goods','m_cat_uid'=>'1','s_cat_uid'=>'46');
$s_cat_data[] = array('s_cat'=>'Subscriptions','m_cat_uid'=>'1','s_cat_uid'=>'47');
$s_cat_data[] = array('s_cat'=>'Tickets','m_cat_uid'=>'1','s_cat_uid'=>'48');
$s_cat_data[] = array('s_cat'=>'Tools','m_cat_uid'=>'1','s_cat_uid'=>'49');
$s_cat_data[] = array('s_cat'=>'Toys','m_cat_uid'=>'1','s_cat_uid'=>'50');
$s_cat_data[] = array('s_cat'=>'Trucks','m_cat_uid'=>'1','s_cat_uid'=>'51');
$s_cat_data[] = array('s_cat'=>'TV\'s','m_cat_uid'=>'1','s_cat_uid'=>'52');
$s_cat_data[] = array('s_cat'=>'Wanted','m_cat_uid'=>'1','s_cat_uid'=>'53');
$s_cat_data[] = array('s_cat'=>'Womens','m_cat_uid'=>'1','s_cat_uid'=>'54');
$s_cat_data[] = array('s_cat'=>'Cannabis','m_cat_uid'=>'1','s_cat_uid'=>'55');
$s_cat_data[] = array('s_cat'=>'Caffeine','m_cat_uid'=>'1','s_cat_uid'=>'56');
$s_cat_data[] = array('s_cat'=>'Wine & Spirits','m_cat_uid'=>'1','s_cat_uid'=>'57');
$s_cat_data[] = array('s_cat'=>'Hemp Products','m_cat_uid'=>'1','s_cat_uid'=>'58');
$s_cat_data[] = array('s_cat'=>'420/710 Rigs','m_cat_uid'=>'1','s_cat_uid'=>'59');
$s_cat_data[] = array('s_cat'=>'Voodoo & Magic','m_cat_uid'=>'1','s_cat_uid'=>'60');
$s_cat_data[] = array('s_cat'=>'Farmers Market','m_cat_uid'=>'1','s_cat_uid'=>'61');
$s_cat_data[] = array('s_cat'=>'Wholesale','m_cat_uid'=>'1','s_cat_uid'=>'62');
$s_cat_data[] = array('s_cat'=>'Booze','m_cat_uid'=>'1','s_cat_uid'=>'63');
$s_cat_data[] = array('s_cat'=>'Smokes','m_cat_uid'=>'1','s_cat_uid'=>'64');
$s_cat_data[] = array('s_cat'=>'Apartments','m_cat_uid'=>'2','s_cat_uid'=>'1');
$s_cat_data[] = array('s_cat'=>'Houses','m_cat_uid'=>'2','s_cat_uid'=>'2');
$s_cat_data[] = array('s_cat'=>'Commercial','m_cat_uid'=>'2','s_cat_uid'=>'3');
$s_cat_data[] = array('s_cat'=>'Land','m_cat_uid'=>'2','s_cat_uid'=>'4');
$s_cat_data[] = array('s_cat'=>'Ranches','m_cat_uid'=>'2','s_cat_uid'=>'5');
$s_cat_data[] = array('s_cat'=>'Real Estate','m_cat_uid'=>'2','s_cat_uid'=>'6');
$s_cat_data[] = array('s_cat'=>'Vacation','m_cat_uid'=>'2','s_cat_uid'=>'7');
$s_cat_data[] = array('s_cat'=>'Accounting','m_cat_uid'=>'3','s_cat_uid'=>'1');
$s_cat_data[] = array('s_cat'=>'Admin & Clerical','m_cat_uid'=>'3','s_cat_uid'=>'2');
$s_cat_data[] = array('s_cat'=>'Agricultural','m_cat_uid'=>'3','s_cat_uid'=>'3');
$s_cat_data[] = array('s_cat'=>'Automotive','m_cat_uid'=>'3','s_cat_uid'=>'4');
$s_cat_data[] = array('s_cat'=>'Banking','m_cat_uid'=>'3','s_cat_uid'=>'5');
$s_cat_data[] = array('s_cat'=>'BioTech','m_cat_uid'=>'3','s_cat_uid'=>'6');
$s_cat_data[] = array('s_cat'=>'Broadcasting','m_cat_uid'=>'3','s_cat_uid'=>'7');
$s_cat_data[] = array('s_cat'=>'Childcare','m_cat_uid'=>'3','s_cat_uid'=>'8');
$s_cat_data[] = array('s_cat'=>'Construction','m_cat_uid'=>'3','s_cat_uid'=>'9');
$s_cat_data[] = array('s_cat'=>'Consultant','m_cat_uid'=>'3','s_cat_uid'=>'10');
$s_cat_data[] = array('s_cat'=>'Contractor','m_cat_uid'=>'3','s_cat_uid'=>'11');
$s_cat_data[] = array('s_cat'=>'Counseling','m_cat_uid'=>'3','s_cat_uid'=>'12');
$s_cat_data[] = array('s_cat'=>'Customer Service','m_cat_uid'=>'3','s_cat_uid'=>'13');
$s_cat_data[] = array('s_cat'=>'Drivers','m_cat_uid'=>'3','s_cat_uid'=>'14');
$s_cat_data[] = array('s_cat'=>'Education','m_cat_uid'=>'3','s_cat_uid'=>'15');
$s_cat_data[] = array('s_cat'=>'Electrical','m_cat_uid'=>'3','s_cat_uid'=>'16');
$s_cat_data[] = array('s_cat'=>'Engineering','m_cat_uid'=>'3','s_cat_uid'=>'17');
$s_cat_data[] = array('s_cat'=>'Executive','m_cat_uid'=>'3','s_cat_uid'=>'18');
$s_cat_data[] = array('s_cat'=>'Facilities','m_cat_uid'=>'3','s_cat_uid'=>'19');
$s_cat_data[] = array('s_cat'=>'Finance','m_cat_uid'=>'3','s_cat_uid'=>'20');
$s_cat_data[] = array('s_cat'=>'General Labor','m_cat_uid'=>'3','s_cat_uid'=>'21');
$s_cat_data[] = array('s_cat'=>'Government','m_cat_uid'=>'3','s_cat_uid'=>'22');
$s_cat_data[] = array('s_cat'=>'Graphic Design','m_cat_uid'=>'3','s_cat_uid'=>'23');
$s_cat_data[] = array('s_cat'=>'Health & Beauty','m_cat_uid'=>'3','s_cat_uid'=>'24');
$s_cat_data[] = array('s_cat'=>'Healthcare','m_cat_uid'=>'3','s_cat_uid'=>'25');
$s_cat_data[] = array('s_cat'=>'Hospitality','m_cat_uid'=>'3','s_cat_uid'=>'26');
$s_cat_data[] = array('s_cat'=>'Human Resources','m_cat_uid'=>'3','s_cat_uid'=>'27');
$s_cat_data[] = array('s_cat'=>'HVAC','m_cat_uid'=>'3','s_cat_uid'=>'28');
$s_cat_data[] = array('s_cat'=>'Insurance','m_cat_uid'=>'3','s_cat_uid'=>'29');
$s_cat_data[] = array('s_cat'=>'Janitorial','m_cat_uid'=>'3','s_cat_uid'=>'30');
$s_cat_data[] = array('s_cat'=>'Legal','m_cat_uid'=>'3','s_cat_uid'=>'31');
$s_cat_data[] = array('s_cat'=>'Logistics','m_cat_uid'=>'3','s_cat_uid'=>'32');
$s_cat_data[] = array('s_cat'=>'Maintenance','m_cat_uid'=>'3','s_cat_uid'=>'33');
$s_cat_data[] = array('s_cat'=>'Management','m_cat_uid'=>'3','s_cat_uid'=>'34');
$s_cat_data[] = array('s_cat'=>'Manufacturing','m_cat_uid'=>'3','s_cat_uid'=>'35');
$s_cat_data[] = array('s_cat'=>'Marketing','m_cat_uid'=>'3','s_cat_uid'=>'36');
$s_cat_data[] = array('s_cat'=>'Materials','m_cat_uid'=>'3','s_cat_uid'=>'37');
$s_cat_data[] = array('s_cat'=>'Networking','m_cat_uid'=>'3','s_cat_uid'=>'38');
$s_cat_data[] = array('s_cat'=>'Nursing','m_cat_uid'=>'3','s_cat_uid'=>'39');
$s_cat_data[] = array('s_cat'=>'Part Time','m_cat_uid'=>'3','s_cat_uid'=>'40');
$s_cat_data[] = array('s_cat'=>'Plumbing','m_cat_uid'=>'3','s_cat_uid'=>'41');
$s_cat_data[] = array('s_cat'=>'Professional Services','m_cat_uid'=>'3','s_cat_uid'=>'42');
$s_cat_data[] = array('s_cat'=>'Project Management','m_cat_uid'=>'3','s_cat_uid'=>'43');
$s_cat_data[] = array('s_cat'=>'Purchasing','m_cat_uid'=>'3','s_cat_uid'=>'44');
$s_cat_data[] = array('s_cat'=>'Real Estate','m_cat_uid'=>'3','s_cat_uid'=>'45');
$s_cat_data[] = array('s_cat'=>'Recruitment','m_cat_uid'=>'3','s_cat_uid'=>'46');
$s_cat_data[] = array('s_cat'=>'Research','m_cat_uid'=>'3','s_cat_uid'=>'47');
$s_cat_data[] = array('s_cat'=>'Restaurant','m_cat_uid'=>'3','s_cat_uid'=>'48');
$s_cat_data[] = array('s_cat'=>'Retail','m_cat_uid'=>'3','s_cat_uid'=>'49');
$s_cat_data[] = array('s_cat'=>'Sales','m_cat_uid'=>'3','s_cat_uid'=>'50');
$s_cat_data[] = array('s_cat'=>'Security','m_cat_uid'=>'3','s_cat_uid'=>'51');
$s_cat_data[] = array('s_cat'=>'Skilled Labor','m_cat_uid'=>'3','s_cat_uid'=>'52');
$s_cat_data[] = array('s_cat'=>'Software','m_cat_uid'=>'3','s_cat_uid'=>'53');
$s_cat_data[] = array('s_cat'=>'Technical','m_cat_uid'=>'3','s_cat_uid'=>'54');
$s_cat_data[] = array('s_cat'=>'Temporary Work','m_cat_uid'=>'3','s_cat_uid'=>'55');
$s_cat_data[] = array('s_cat'=>'Training','m_cat_uid'=>'3','s_cat_uid'=>'56');
$s_cat_data[] = array('s_cat'=>'Transportation','m_cat_uid'=>'3','s_cat_uid'=>'57');
$s_cat_data[] = array('s_cat'=>'Veterinary','m_cat_uid'=>'3','s_cat_uid'=>'58');
$s_cat_data[] = array('s_cat'=>'Volunteer','m_cat_uid'=>'3','s_cat_uid'=>'59');
$s_cat_data[] = array('s_cat'=>'Work From Home','m_cat_uid'=>'3','s_cat_uid'=>'60');
$s_cat_data[] = array('s_cat'=>'Horticulture','m_cat_uid'=>'3','s_cat_uid'=>'61');
$s_cat_data[] = array('s_cat'=>'Women','m_cat_uid'=>'4','s_cat_uid'=>'1');
$s_cat_data[] = array('s_cat'=>'Men','m_cat_uid'=>'4','s_cat_uid'=>'2');
$s_cat_data[] = array('s_cat'=>'LGBT','m_cat_uid'=>'4','s_cat_uid'=>'3');
$s_cat_data[] = array('s_cat'=>'Platonic','m_cat_uid'=>'4','s_cat_uid'=>'4');
$s_cat_data[] = array('s_cat'=>'Escorts','m_cat_uid'=>'4','s_cat_uid'=>'5');
$s_cat_data[] = array('s_cat'=>'Automotive','m_cat_uid'=>'5','s_cat_uid'=>'1');
$s_cat_data[] = array('s_cat'=>'Bridal & Wedding','m_cat_uid'=>'5','s_cat_uid'=>'2');
$s_cat_data[] = array('s_cat'=>'Clothing & Apparel','m_cat_uid'=>'5','s_cat_uid'=>'3');
$s_cat_data[] = array('s_cat'=>'Computers','m_cat_uid'=>'5','s_cat_uid'=>'4');
$s_cat_data[] = array('s_cat'=>'Contruction','m_cat_uid'=>'5','s_cat_uid'=>'5');
$s_cat_data[] = array('s_cat'=>'Crafts','m_cat_uid'=>'5','s_cat_uid'=>'6');
$s_cat_data[] = array('s_cat'=>'Electronics','m_cat_uid'=>'5','s_cat_uid'=>'7');
$s_cat_data[] = array('s_cat'=>'Entertainment','m_cat_uid'=>'5','s_cat_uid'=>'8');
$s_cat_data[] = array('s_cat'=>'Financing','m_cat_uid'=>'5','s_cat_uid'=>'9');
$s_cat_data[] = array('s_cat'=>'Food & Groceries','m_cat_uid'=>'5','s_cat_uid'=>'10');
$s_cat_data[] = array('s_cat'=>'Gardening & Landscaping','m_cat_uid'=>'5','s_cat_uid'=>'11');
$s_cat_data[] = array('s_cat'=>'Graphic Design','m_cat_uid'=>'5','s_cat_uid'=>'12');
$s_cat_data[] = array('s_cat'=>'Health & Beauty','m_cat_uid'=>'5','s_cat_uid'=>'13');
$s_cat_data[] = array('s_cat'=>'Holiday & Seasonal','m_cat_uid'=>'5','s_cat_uid'=>'14');
$s_cat_data[] = array('s_cat'=>'Home Decor','m_cat_uid'=>'5','s_cat_uid'=>'15');
$s_cat_data[] = array('s_cat'=>'Home Entertainment','m_cat_uid'=>'5','s_cat_uid'=>'16');
$s_cat_data[] = array('s_cat'=>'Home Improvement','m_cat_uid'=>'5','s_cat_uid'=>'17');
$s_cat_data[] = array('s_cat'=>'Hotel & Lodging','m_cat_uid'=>'5','s_cat_uid'=>'18');
$s_cat_data[] = array('s_cat'=>'Hunting & Fishing','m_cat_uid'=>'5','s_cat_uid'=>'19');
$s_cat_data[] = array('s_cat'=>'Legal','m_cat_uid'=>'5','s_cat_uid'=>'20');
$s_cat_data[] = array('s_cat'=>'Literature','m_cat_uid'=>'5','s_cat_uid'=>'21');
$s_cat_data[] = array('s_cat'=>'Moving & Storage','m_cat_uid'=>'5','s_cat_uid'=>'22');
$s_cat_data[] = array('s_cat'=>'Music & Concerts','m_cat_uid'=>'5','s_cat_uid'=>'23');
$s_cat_data[] = array('s_cat'=>'Outdoor Recreation','m_cat_uid'=>'5','s_cat_uid'=>'24');
$s_cat_data[] = array('s_cat'=>'Outdoor Sporting','m_cat_uid'=>'5','s_cat_uid'=>'25');
$s_cat_data[] = array('s_cat'=>'Pet Grooming','m_cat_uid'=>'5','s_cat_uid'=>'26');
$s_cat_data[] = array('s_cat'=>'Professional Services','m_cat_uid'=>'5','s_cat_uid'=>'27');
$s_cat_data[] = array('s_cat'=>'Restaurant & Dining','m_cat_uid'=>'5','s_cat_uid'=>'28');
$s_cat_data[] = array('s_cat'=>'Retail','m_cat_uid'=>'5','s_cat_uid'=>'29');
$s_cat_data[] = array('s_cat'=>'Software','m_cat_uid'=>'5','s_cat_uid'=>'30');
$s_cat_data[] = array('s_cat'=>'Travel','m_cat_uid'=>'5','s_cat_uid'=>'31');
$s_cat_data[] = array('s_cat'=>'Horticulture','m_cat_uid'=>'5','s_cat_uid'=>'32');
?>
